### ISSUE TITLE
Shorten folder names to avoid max_path issues

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Identity#1387]
Discussed in-person with @javiercn. We should try to shorten the folder names in this repo to avoid max_path issues on Windows.

E.g. opening in VS can cause this:
![image](https://user-images.githubusercontent.com/2696087/29591173-2c231682-8752-11e7-99a5-65f43bbf04af.png)

**Comment by natemcmaster** [comment]
cref https://github.com/aspnet/Universe/issues/531

**Comment by HaoK** [comment]
Yes please, git clean -xdff hates those long file names...

**Comment by natemcmaster** [comment]
This one needs some discussion first. Most repos had a common prefix, like Microsoft.Extensions, which made it easy to decide how to shorten the names. This one has a mix of a several prefixes: Microsoft.AspNet., Microsoft.AspNetCore, and Microsoft.Extensions.

**Comment by HaoK** [comment]
I'd suggest:

AspNetCoreCompat
Core.Diagonstics.XIdentity
Core.Identity.Xyz
Extensions.Identity.Xyz

@javiercn is in the process of moving some of these around/collapsing some but I think that covers all of the general buckets

**Comment by HaoK** [comment]
Ideally if we end up with everything having Identity in the name here, we could drop that off too.

AspNet.CoreCompat
Core
Core.Diagnostics
Core.EntityFramework
Core.Service.Xyz
Core.SpecificationTests
Extensions.Core
Extensions.Stores

**Comment by natemcmaster** [comment]
I'm curious. Is this working for anyone else? I moved the repo to the shortest possible folder and even then I still can't use `C:\i\Identity.sln` because of  this one:
> test\Microsoft.AspNetCore.Identity.Service.EntityFrameworkCore.InMemory.Test\Microsoft.AspNetCore.Identity.Service.EntityFrameworkCore.InMemory.Test.csproj

**Comment by javiercn** [comment]
@natemcmaster I see that issue on VS, but everything works for me.

**Comment by PinpointTownes** [comment]
Shortening all the project paths is probably a simple option, but it makes navigating across tags/branches a total PITA (not to mention that you also loose all the changes history associated with a file). Yet, I'm sure many folks (including me) use that as a way to determine what's changed between 2 ASP.NET Core versions :sweat: 

Personally, I've opted for a better workaround that forces MSBuild to use shorter filenames for its binding redirect files (that are insanely long by default :open_mouth:):

```xml
<Target Name="WorkaroundAppConfigPathTooLong" BeforeTargets="GenerateBindingRedirects">
  <PropertyGroup>
    <_GenerateBindingRedirectsIntermediateAppConfig>$(IntermediateOutputPath)$(TargetFileName).config</_GenerateBindingRedirectsIntermediateAppConfig>
  </PropertyGroup>
</Target>
```

**Comment by javiercn** [comment]
@natemcmaster Is there a better way to do this than to shorten the paths?

**Comment by natemcmaster** [comment]
Depends on what you're optimizing for. If you're optimizing for git history and GitHub browsing, renaming a folder is not the best approach. However, shorter folder names are the simplest way to solve the issue, and is one we've already implemented in other projects such as EF and Kestrel.

There are other options. As @PinpointTownes points out, you can try working around by changing individual files with MSBuild properties. You can lift obj/ and bin/ to the solution folder. You rename just the longest folders. You can rename just the csproj filename. etc. 

IIRC you said there was a plan to rename the project folders and reorganize code anyways, so IMO you might as well shorten the folder name when you do this.

**Comment by HaoK** [comment]
I already renamed folders in 2.0 and moved files around, so doing it again is unlikely to make things that much worse

**Comment by HaoK** [comment]
The file names are still the same, so they can always navigate to the branch/tag and search for the file, its not that unreasonable

**Comment by PinpointTownes** [comment]
> I already renamed folders in 2.0 and moved files around, so doing it again is unlikely to make things that much worse

My remark was not limited to this repo (I suppose this plan is going to be adopted globally for consistency). Fortunately, Identity is pretty much the only repository whose structure was radically changed in 2.x :sweat_smile:

**Comment by natemcmaster** [comment]
Current thinking on https://github.com/aspnet/Universe/issues/531 is that we'll only shorten folders in repos as required. Identity is _definitely_ one of those cases.

**Comment by HaoK** [comment]
@natemcmaster is this still an issue we want to fix? I can submit a PR with some shortened names if we still want to do this...  I personally hate seeing this warning too so I'm all for it

**Comment by natemcmaster** [comment]
Yes, let's fix it. I think we held off on this because there was expected to be a lot of churn. But that should have settled by now, right?

**Comment by natemcmaster** [comment]
FYI - since the issue was almost always a file in obj/ or bin/, another solution that works well is setting BaseIntermediateOutputPath and BaseOutputPath using Directory.Build.props. Maybe we should try that first. We did this in aspnet/DotNetTools and haven't had problems so far.

https://github.com/aspnet/DotNetTools/blob/dev/Directory.Build.props#L23-L24

**Comment by HaoK** [comment]
here's what I'm thinking, I don't think you lose any meaning by just going with these folders:

```
AspNetCoreCompat (Microsoft.AspNet.Identity.AspNetCoreCompat)
Core (Microsoft.Extensions.Identity.Core)
Stores (Microsoft.Extensions.Identity.Stores)
Identity (Microsoft.AspNetCore.Identity)
Service.* ((Microsoft.AspNetCore.Identity.Service.*)
```

**Comment by HaoK** [comment]
85f8a49aef68bf9763cd9854ce1dd4a26a7c5d3c
